# Generated by Django 5.1.4 on 2024-12-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_question_answer_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsessionprogress',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
